### ISSUE TITLE
When there is a buffer title collision, try using the name of the scripty directory as a suffix

### ISSUE THREAD

**Issue by jwalgran** [steventlamb/scripty-client.el#3]

**Comment by steventlamb** [comment]
This requires some thought, because this is my second time facing this problem and I haven't formed a clear opinion.

I think the desired behavior is specific to the user and the given command. For example, I like my flake8 checks to just use the same buffer, I don't want to accumulate a lot of buffers. I like that it overwrites. For unit tests, I like the forensic flexibility, so I would like it to work as you describe.

Do you have any thoughts on this aspect of the problem?

**Comment by jwalgran** [comment]
I like the prompt and being given the choice to make a new buffer. I guess the ``<2>`` suffix is more idiomatic to Emacs.

If there is already a buffer open, having a third option to kill it and start a new one would be useful (in addition to open a new buffer, or bail).
